sudo: required
services:
  - docker

script:
  - docker build -t mdigbazova/docker_travis .
  - docker images mdigbazova/docker_travis 

before_deploy:
  - docker login -u foretell -p 1Q!KraliMarko 

deploy:
 provider: script
 #foretell/tests
 script: docker push mdigbazova/docker_travis 
 on:
    branch: master


